package com.chimera.ai

import com.chimera.model.CharacterState
import com.chimera.model.DialogueTurnResult
import com.chimera.model.MemoryShard
import com.chimera.model.PlayerInput
import com.chimera.model.SceneContract

/**
 * Routes dialogue requests through an ordered chain of AI providers.
 * Tries each provider in sequence; falls back on failure.
 *
 * Default chain: Gemini → Groq → OpenRouter
 * (FakeDialogueProvider fallback is handled by DialogueOrchestrator)
 */
class ProviderRouter(
    val providers: List<NamedProvider>
) : DialogueProvider {

    data class NamedProvider(val name: String, val provider: DialogueProvider)

    var activeProviderName: String = "none"
        private set

    override suspend fun generateTurn(
        contract: SceneContract,
        playerInput: PlayerInput,
        characterState: CharacterState,
        recentMemories: List<MemoryShard>,
        turnHistory: List<DialogueTurnResult>
    ): DialogueTurnResult {
        for (named in providers) {
            try {
                if (!named.provider.isAvailable()) continue
                val result = named.provider.generateTurn(
                    contract, playerInput, characterState, recentMemories, turnHistory
                )
                activeProviderName = named.name
                println("DEBUG: ProviderRouter - Turn generated by ${named.name}")
                return result
            } catch (e: Exception) {
                println("WARN: ProviderRouter - ${named.name} failed: ${e.message}")
            }
        }
        throw Exception("All cloud providers failed")
    }

    override suspend fun generateIntents(
        contract: SceneContract,
        characterState: CharacterState,
        turnHistory: List<DialogueTurnResult>
    ): List<String> {
        for (named in providers) {
            try {
                if (!named.provider.isAvailable()) continue
                val intents = named.provider.generateIntents(contract, characterState, turnHistory)
                if (intents.isNotEmpty()) return intents
            } catch (e: Exception) {
                println("WARN: ProviderRouter - ${named.name} intents failed: ${e.message}")
            }
        }
        throw Exception("All cloud providers failed for intents")
    }

    override suspend fun isAvailable(): Boolean {
        return providers.any { runCatching { it.provider.isAvailable() }.getOrDefault(false) }
    }
}
