#!/usr/bin/env bash
# RELEASE phase: push branch, create PR, release-prep go/no-go, merge
set -euo pipefail
STATE="$(git rev-parse --show-toplevel)/scripts/chimera-sdlc/state"

SPRINT=$(python3 -c "import json; print(json.load(open('scripts/chimera-sdlc/state/sprint-context.json'))['sprint_version'])")
BRANCH=$(python3 -c "import json; print(json.load(open('scripts/chimera-sdlc/state/sprint-context.json'))['branch'])")
COMPLETED=$(python3 -c "import json; ctx=json.load(open('scripts/chimera-sdlc/state/sprint-context.json')); print(', '.join(ctx['completed_tasks']))")

echo "[RELEASE] Sprint: $SPRINT | Branch: $BRANCH"
git push origin +HEAD:"$BRANCH" 2>&1

PR_URL=$(gh pr create \
  --title "feat: Chimera sprint $SPRINT — SDLC auto-release" \
  --body "## Summary
Auto-generated by chimera-sdlc orchestrator.
Tasks: $COMPLETED

## Self-Correction Log
$(tail -5 scripts/chimera-sdlc/state/correction-log.md)

🤖 Generated with [Claude Code](https://claude.com/claude-code)" \
  --base main 2>&1)

echo "[RELEASE] PR: $PR_URL"

RESULT=$(claude --print "Run the release-prep agent for sprint $SPRINT. Read correction-log at scripts/chimera-sdlc/state/correction-log.md. Emit go/no-go checklist." 2>&1)
if echo "$RESULT" | grep -q "GO"; then
  PR_NUMBER=$(echo "$PR_URL" | grep -o '[0-9]*$')
  gh pr merge "$PR_NUMBER" --merge --subject "feat: Chimera sprint $SPRINT — SDLC auto-release"
  echo "reflect" > "$STATE/current-phase.txt"
  echo "[RELEASE] Merged → REFLECT"
else
  echo "[RELEASE] NO-GO — human review required"
  echo "release-blocked" > "$STATE/current-phase.txt"
  exit 1
fi
