name: Android CI/CD - Project Chimera

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Unit Tests

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run tests
      run: ./gradlew test

    - name: Upload test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-reports
        path: app/build/reports/tests/

  build:
    runs-on: ubuntu-latest
    needs: test
    name: Build APK

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: project-chimera-debug-apk
        path: app/build/outputs/apk/debug/*.apk

    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: project-chimera-release-apk
        path: app/build/outputs/apk/release/*.apk

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy Demo
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Demo APK
      run: ./gradlew assembleDemo

    - name: Upload Demo APK
      uses: actions/upload-artifact@v3
      with:
        name: project-chimera-demo-apk
        path: app/build/outputs/apk/demo/*.apk

    - name: Create Release
      uses: actions/create-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Project Chimera ${{ github.ref }}
        body: |
          🧠 Project Chimera - Revolutionary AI-Driven NPC Consciousness
          
          This release includes:
          - Complete SystemArchetypeEngine with behavioral psychology patterns
          - Production-ready Android UI with consciousness monitoring
          - Emergent NPC behavior through Systems Thinking implementation
          
          Download the APK to experience the future of NPC consciousness!
        draft: false
        prerelease: false