- name: Build Release APK
  run: ./gradlew assembleRelease
  working-directory: ./android

- name: Upload Release APK
  uses: actions/upload-artifact@v3
  with:
    name: app-release
    path: android/app/build/outputs/apk/release/app-release.apk
- name: Create keystore file
  env:
    KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
  run: |
    echo $KEYSTORE_BASE64 | base64 --decode > android/app/keystore.jks

- name: Build Signed Release APK
  env:
    KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
    KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
    KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  run: ./gradlew assembleRelease
  working-directory: ./android
name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./android
    
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./android
    
    - name: Run tests
      run: ./gradlew test
      working-directory: ./android
    
    # Debug APK (existing)
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
    
    # Release APK (new)
    - name: Build Release APK
      run: ./gradlew assembleRelease
      working-directory: ./android
    
    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: android/app/build/outputs/apk/release/app-release.apk

  # ... rest of your workflow remains the same
